### ISSUE TITLE
[Track 2] train BEVerse meet error

### ISSUE THREAD

**Issue by weiyuelu** [robodrive-24/toolkit#4]
I've followed the installation.md and make the virtual environment, but meet this question when python train.py configs
`Traceback (most recent call last):
  File "tools/test.py", line 14, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/workdir/weiyuelu/BEVerse/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/workdir/weiyuelu/BEVerse/mmdet3d/apis/inference.py", line 11, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes,
  File "/workdir/weiyuelu/BEVerse/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/workdir/weiyuelu/BEVerse/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/workdir/miniforge3/envs/py37/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/workdir/miniforge3/envs/py37/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
`

**Comment by robodrive-24** [comment]
Hi @weiyuelu , thanks for your participation in the RoboDrive challenge!

Regarding your question:

- This might be due to the incompatibility between `mmcv` and `torch` version. You can search the issue in [mmcv repo](https://github.com/open-mmlab/mmcv) for more detailed discussion.
- It's suggested to specify `torch` version when installing `mmcv` package, you can refer to the installation on this [page](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/install.md) and replace the version with what you need.


Let us know if the above solves your problem!
