### ISSUE TITLE
cannot import name 'track_iter_progress' from 'mmcv.utils'

### ISSUE THREAD

**Issue by shigengtian** [robodrive-24/toolkit#5]
There is an error
`cannot import name 'track_iter_progress' from 'mmcv.utils'`
 when run the toolkit to prepare data for track-1

Can you share more information about the mm3d version to run the baseline?

**Comment by robodrive-24** [comment]
Hi @shigengtian , thanks for your participation in the RoboDrive challenge!

Regarding your question:

- Could you please provide the full context information of the error?
- This error is might due to version incompatibility. Please make sure to install the `mmcv` with the compatible `torch` version. It's suggested to install `mmcv` using:
```bash
# specify version
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
```

Let us know if the above solves your problem!

**Comment by robodrive-24** [comment]
Hi Gengtian,

Thanks for your interest in the RoboDrive Challenge!

We've answered your questions on the Github page. Please kindly refer to
the Github issue page.

Thanks!

Regards,
RoboDriver

**Comment by eii-shi** [comment]
Hi @robodrive-24 
thank you very much!

**Comment by MrGoldminer** [comment]
ImportError: cannot import name 'track_iter_progress' from 'mmcv' (unknown location)
then this have this error?

**Comment by MrGoldminer** [comment]
-packages/mmdetection3d/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 11, in <module>
    from mmdet3d.core.bbox import box_np_ops as box_np_ops
  File "/home/goldminer/miniconda3/envs/open-mmlab/lib/python3.8/site-packages/mmdet3d-1.4.0-py3.8.egg/mmdet3d/__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.2.0.
and this problem

**Comment by MrGoldminer** [comment]
and change to 2.0.0rc4 ,will have a error
(bev) goldminer@goldminer:~/mmdetection3d/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 5, in <module>
    from mmcv import track_iter_progress
ImportError: cannot import name 'track_iter_progress' from 'mmcv' (/home/goldminer/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/__init__.py)

**Comment by MrGoldminer** [comment]
and change to 2.0.0rc4 ,will have a error
(bev) goldminer@goldminer:~/mmdetection3d/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 5, in <module>
    from mmcv import track_iter_progress
ImportError: cannot import name 'track_iter_progress' from 'mmcv' (/home/goldminer/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/__init__.py)

**Comment by MrGoldminer** [comment]
and change to 2.0.0rc4 ,will have a error
(bev) goldminer@goldminer:~/mmdetection3d/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 5, in <module>
    from mmcv import track_iter_progress
ImportError: cannot import name 'track_iter_progress' from 'mmcv' (/home/goldminer/miniconda3/envs/bev/lib/python3.8/site-packages/mmcv/__init__.py)

**Comment by MrGoldminer** [comment]
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 11, in <module>
    from mmdet3d.core.bbox import box_np_ops as box_np_ops
  File "/home/goldminer/miniconda3/envs/bev/lib/python3.8/site-packages/mmdet3d-1.4.0-py3.8.egg/mmdet3d/__init__.py", line 3, in <module>
THIS ERROR not have connection with up.so i don not how to fix it

**Comment by MrGoldminer** [comment]
还是有这个问题：(bev) goldminer@goldminer:~/mmdetection3d/BEVFormer$ python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini --canbus ./data
Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from data_converter.create_gt_database import create_groundtruth_database
  File "/home/goldminer/mmdetection3d/BEVFormer/tools/data_converter/create_gt_database.py", line 5, in <module>
    from mmcv import track_iter_progress
ImportError: cannot import name 'track_iter_progress' from 'mmcv' (unknown location)
